### ISSUE TITLE
Assorted errors on last master

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#127]
On a rocky8:
```
Traceback (most recent call last):
File "/home/simdaemon/svn/mappotiles/local_arkimaps/arkimaps", line 19, in <module>
from arkimapslib.flavours import Flavour
File "/home/simdaemon/svn/mappotiles/local_arkimaps/arkimapslib/flavours.py", line 11, in <module>
from . import recipes
File "/home/simdaemon/svn/mappotiles/local_arkimaps/arkimapslib/recipes.py", line 9, in <module>
from . import toposort
File "/home/simdaemon/svn/mappotiles/local_arkimaps/arkimapslib/toposort.py", line 1
 from __future__ import annotations
 ^
 SyntaxError: future feature annotations is not defined
```

On Fedora 36 there is a test failure: https://simc.arpae.it/moncic-ci/arkimaps/202212061110/master/fedora36/build.log

**Comment by spanezz** [comment]
Try again, both issues should be fixed now
