### ISSUE TITLE
Errore "No such file or directory" per dati decumulati non presenti

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#130]
Situazione:
dispatch + render in due tempi, l'errore viene innescato dall'assenza di una cumulata presente fra le recipes (es: neve a 1h per ifs dove è assente, pioggia a 24h per cosmo_2I_ruc che arriva al massimo alla +18)

In allegato la situazione post-dispatch e pre-render del prodotto TP, incluse recipes:
[cosmo_2I_ruc_test.tar.gz](https://github.com/ARPA-SIMC/arkimaps/files/10237044/cosmo_2I_ruc_test.tar.gz)

(nota: nel flavour `ita_small_tiles` è esplicitato un `recipes_filter` sulla ricetta incriminata ma anche togliendolo il risultato è analogo)

log dell'esecuzione fallita:
```
Comando timeout -v 2h bash -c "/home/dbranchini@ARPA.EMR.NET/svn/salopdevel/mappotiles/local_arkimaps/arkimaps render --recipes=/tmp/d_devel.crontab.salop.mappotiles.cosmo_2I_ruc.00.by6LVB9oAP/recipes --flavour ita_small_tiles /tmp/d_devel.crontab.salop.mappotiles.cosmo_2I_ruc.00.by6LVB9oAP/dispatch -o out.tar" uscito con errore 1. Segue log.
Traceback (most recent call last):
File "/home/dbranchini@ARPA.EMR.NET/svn/salopdevel/mappotiles/local_arkimaps/arkimaps", line 471, in <module>
main()
File "/home/dbranchini@ARPA.EMR.NET/svn/salopdevel/mappotiles/local_arkimaps/arkimaps", line 462, in main
res = handler.run()
File "/home/dbranchini@ARPA.EMR.NET/svn/salopdevel/mappotiles/local_arkimaps/arkimaps", line 351, in run
self.render_tarball()
File "/home/dbranchini@ARPA.EMR.NET/svn/salopdevel/mappotiles/local_arkimaps/arkimaps", line 134, in render_tarball
orders += self.kitchen.make_orders(flavour=flavour)
File "/home/dbranchini@ARPA.EMR.NET/svn/salopdevel/mappotiles/local_arkimaps/arkimapslib/kitchen.py", line 139, in make_orders
res.extend(flavour.make_orders(recipe, self.pantry))
File "/home/dbranchini@ARPA.EMR.NET/svn/salopdevel/mappotiles/local_arkimaps/arkimapslib/flavours.py", line 170, in make_orders
output_instants = pantry.get_instants(input_name)
File "/home/dbranchini@ARPA.EMR.NET/svn/salopdevel/mappotiles/local_arkimaps/arkimapslib/pantry.py", line 202, in get_instants
instants = inp.get_instants(self)
File "/home/dbranchini@ARPA.EMR.NET/svn/salopdevel/mappotiles/local_arkimaps/arkimapslib/inputs.py", line 408, in get_instants
self.generate(pantry)
File "/home/dbranchini@ARPA.EMR.NET/svn/salopdevel/mappotiles/local_arkimaps/arkimapslib/inputs.py", line 501, in generate
size = os.path.getsize(decumulated_data)
File "/usr/lib64/python3.10/genericpath.py", line 50, in getsize
return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/d_devel.crontab.salop.mappotiles.cosmo_2I_ruc.00.by6LVB9oAP/dispatch/pantry/tpdec24h-decumulated.grib'
```

**Comment by spanezz** [comment]
Riprodotto con `arkimaps --debug render --flavour=ita_small_tiles wd_issue130/dispatch/ -o out.tar  --recipes wd_issue130/recipes/`

**Comment by spanezz** [comment]
Sistemato sia in master che in schedule
