### ISSUE TITLE
problema aggiunta geopoint e shapefile custom

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#144]
Se provo ad aggiungere geopoint (via flavour o via ricetta) ad esempio con:
```
 - step: add_geopoints
   params:
     geo_input_file_name: "/tmp/sea_punti.geo"
```

Ottengo un errore non chiaro:
```
$ ./arkimaps preview t1/ --flavour=sea_tos standalone/sea_swhdir
Traceback (most recent call last):
  File "/home/branco/git/arkimaps/./arkimaps", line 468, in <module>
    main()
  File "/home/branco/git/arkimaps/./arkimaps", line 459, in main
    res = handler.run()
  File "/home/branco/git/arkimaps/./arkimaps", line 393, in run
    order = self.kitchen.make_order(self.kitchen.recipes.get(name), flavour=flavour, step=step, reftime=reftime)
  File "/home/branco/git/arkimaps/arkimapslib/kitchen.py", line 157, in make_order
    for o in flavour.make_orders(recipe, self.pantry):
  File "/home/branco/git/arkimaps/arkimapslib/flavours.py", line 191, in make_orders
    return self.inputs_to_orders(recipe, inputs, inputs_for_all_instants)
  File "/home/branco/git/arkimaps/arkimapslib/flavours.py", line 216, in inputs_to_orders
    res.append(orders.MapOrder(
  File "/home/branco/git/arkimaps/arkimapslib/orders.py", line 167, in __init__
    s = recipe_step.step(recipe_step.name, step_config, recipe_step.args, input_files)
  File "/home/branco/git/arkimaps/arkimapslib/steps.py", line 308, in __init__
    raise KeyError(f"{self.name}: input {input_name} not found. Available: {', '.join(sources.keys())}")
KeyError: 'add_geopoints: input None not found. Available: swh, seaswhdir'
```
I due input che cita come "available" sono i due products grib usati per quella mappa.

Stessa cosa se provo ad aggiungere uno shapefile alla sezione `add_user_boundaries` (ovviamente con errore relativo a quella sezione).

**Comment by spanezz** [comment]
Sí, `static_dir` è definita in https://github.com/ARPA-SIMC/arkimaps/blob/master/arkimapslib/inputs.py#L246 come una directory tra i sorgenti di arkimaps.

Possiamo allargare la cosa a piú static dir, tipo quella attuale e la directory delle ricette. O meglio forse una sottodirectory `static/` dentro alle ricette?
