### ISSUE TITLE
analisi performance

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#20]
Ho fatto un test di quelli violenti:
```
$ arki-query --inline 'reftime:=yesterday 00:00' http://arkimet.metarpa:8090/dataset/cosmo_5M_ita > test.arkimet
$ ./arkimaps < test.arkimet 
```
Parliamo di 3.7 Gb di dati (per dare un termine di paragone i file della corsa vengono importati in arkimet in circa 4 minuti, incluso lo scaricamento da Cineca)

Dopo 38 minuti è uscito con un illegal seek:
```
$ ./arkimaps < test.arkimet 
Traceback (most recent call last):
  File "./arkimaps", line 180, in <module>
    main()
  File "./arkimaps", line 175, in main
    arkimaps.do_render()
  File "./arkimaps", line 102, in do_render
    with self.open_output() as tarout:
  File "./arkimaps", line 96, in open_output
    return tarfile.open(mode="x", fileobj=sys.stdout.buffer)
  File "/usr/lib64/python3.7/tarfile.py", line 1611, in open
    return cls.taropen(name, mode, fileobj, **kwargs)
  File "/usr/lib64/python3.7/tarfile.py", line 1621, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib64/python3.7/tarfile.py", line 1476, in __init__
    self.offset = self.fileobj.tell()
OSError: [Errno 29] Illegal seek
```

Ora, ad là dell'errore, i tempi dello smistamento dati mi sembrano abbastanza preoccupanti anche al netto di alcune migliorie possibili (la modifica su eatmydata che non è ancora stata inclusa in una release arkimet o un eventuale spostamento della dir di lavoro su /dev/shm)

A meno che non ci sia qualcosa di macroscopico che mi sfugge (possibilissimo), mi aspettavo che mantenere i metadata di arkimet al posto di ricavarli unicamente dai grib avesse un costo ma se lo scarto rispetto ad un banale `grib_filter` in append diventa così grande il costo supera un po' troppo i benefici.

Chiaramente per i processi operativi la query sarà tarata un po' meglio, faccio qualche prova anche in questo senso.

**Comment by brancomat** [comment]
Il discorso performance sta diventando articolato, ho aperto #125 e #126 e in generale trasferirei il discorso su temi specifici isolati in singole issues, chiudo questa
