### ISSUE TITLE
supporto a python 3.6

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#57]
prendendo come doloroso dato assiomatico che arkimaps in produzione girerà su CentOS8 (python 3.6), mi sono stampato come un cerbiatto davanti ai tir della statale con le seguenti problematiche (prontamente soccorso da @edigiacomo):

1) `from __future__ import annotations` c'è solo da python 3.7
l'idea iniziale di renderlo condizionale si è scontrata con un
```
SyntaxError: from __future__ imports must occur at the beginning of the file
```
Nel branch `ifs_grib2` ho temporaneamente commentato.

2) la postponed evaluation of annotations di `typing.TYPE_CHECKING` c'è (indovina?) solo da python 3.7. Qui la soluzione [è un poco più semplice, ma ti lascia con un po' di PTSD](https://i.imgflip.com/4y4w8a.jpg).

3) `module 'time' has no attribute 'clock_gettime_ns'`. Devo dire anche da che versione l'hanno introdotta? Hint: finisce per `.7`

questa non l'ho ancora sistemato, ho provato banalmente a modificarla in una `clock_gettime` ma poi mi è esploso su un `TypeError: can't pickle _thread.RLock objects` che non ho capito se sia collegato o se sia una pesca scollegata

**Comment by spanezz** [comment]
Direi che si possano commentare tutti i `from future import` e gli `if TYPE_CHECKING` e tutto il loro contenuto, virgolettando poi i vari tipi nelle signature che non vengono importati

**Comment by spanezz** [comment]
E io che speravo di poter fare type checking un pochino meglio del codice una volta che diventa bello stabile, e invece... :(

**Comment by brancomat** [comment]
Avevo già optato per non rimuovere gli `if TYPE_CHECKING` perché virgolettando in maniera opportuna mi pareva si potessero mantenere.
Ho modificato anche la `clock_gettime_ns` in `clock_gettime`.

Ora però sono fermo su un errore più inquietante fuori dal mio campionato (per la riproducibilità, allego grib che ho usato: [ifs.tar.gz](https://github.com/ARPA-SIMC/arkimaps/files/5994560/ifs.tar.gz), il branch su cui sto lavorando è `ifs_grib2` e un server su cui testare è `otto.metarpa`, ma possiamo lavorare al contrario, se il master funziona su `otto.metarpa` mi va poi bene uguale):

```
$ ./arkimaps --debug process --filter eccodes  -o out.tar < test_data/grib2_ifs.arkimet 
2021-02-17 10:08:26,707 INFO litota3_ita: 32 orders created
2021-02-17 10:08:26,708 INFO litota3_emr: 32 orders created
2021-02-17 10:08:26,709 DEBUG viwvn_emr+000: data for input mcont not found: skipping
2021-02-17 10:08:26,710 INFO viwvn_emr: 32 orders created
2021-02-17 10:08:26,711 DEBUG viwve_ita+000: data for input viwve not found: skipping
2021-02-17 10:08:26,712 INFO viwve_ita: 32 orders created
2021-02-17 10:08:26,713 INFO litota3_nord: 32 orders created
2021-02-17 10:08:26,714 DEBUG viwvn_ita+000: data for input mcont not found: skipping
2021-02-17 10:08:26,715 INFO viwvn_ita: 32 orders created
2021-02-17 10:08:26,716 DEBUG viwve_emr+000: data for input viwve not found: skipping
2021-02-17 10:08:26,717 INFO viwve_emr: 32 orders created
Traceback (most recent call last):
  File "./arkimaps", line 365, in <module>
    main()
  File "./arkimaps", line 356, in main
    res = handler.run()
  File "./arkimaps", line 305, in run
    self.render_tarball()
  File "./arkimaps", line 106, in render_tarball
    for order in renderer.render(orders):
  File "/autofs/nfshomes/dbranchini/git/arkimaps/arkimapslib/render.py", line 63, in render
    yield from pool.imap_unordered(prepare_order, orders)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
    put(task)
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 210, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib64/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects
```

**Comment by spanezz** [comment]
master ora passa la test suite su `otto.metarpa`. Se mi confermi che ti gira anche in produzione, direi che possiamo chiudere

**Comment by brancomat** [comment]
Mi risulta lo stesso identico problema del mio ultimo commento:

```
[dbranchini@otto arkimaps]$ ./arkimaps --debug process --filter eccodes  -o out.tar < test_data/grib2_ifs.arkimet 
2021-02-24 17:15:17,274 INFO cp12h: 0 orders created
2021-02-24 17:15:17,275 INFO lcc: 0 orders created
2021-02-24 17:15:17,275 INFO z700: 0 orders created
2021-02-24 17:15:17,275 INFO tp12h: 0 orders created
2021-02-24 17:15:17,275 INFO t500: 0 orders created
2021-02-24 17:15:17,276 DEBUG viwve+000: data for input viwve not found: skipping
2021-02-24 17:15:17,277 INFO viwve: 32 orders created
2021-02-24 17:15:17,277 INFO tp1h: 0 orders created
2021-02-24 17:15:17,278 INFO litota3: 32 orders created
2021-02-24 17:15:17,278 INFO z250: 0 orders created
2021-02-24 17:15:17,279 DEBUG viwvn+000: data for input mcont not found: skipping
2021-02-24 17:15:17,280 INFO viwvn: 32 orders created
2021-02-24 17:15:17,280 INFO z850: 0 orders created
2021-02-24 17:15:17,280 INFO tp24h: 0 orders created
2021-02-24 17:15:17,281 INFO t925: 0 orders created
2021-02-24 17:15:17,281 INFO t700: 0 orders created
2021-02-24 17:15:17,281 INFO cp24h: 0 orders created
2021-02-24 17:15:17,281 INFO tp6h: 0 orders created
2021-02-24 17:15:17,281 INFO cp6h: 0 orders created
2021-02-24 17:15:17,282 INFO hcc: 0 orders created
2021-02-24 17:15:17,283 INFO mslp: 33 orders created
2021-02-24 17:15:17,283 INFO tp3h: 0 orders created
2021-02-24 17:15:17,283 INFO cp3h: 0 orders created
2021-02-24 17:15:17,283 INFO tcc: 0 orders created
2021-02-24 17:15:17,283 INFO t850: 0 orders created
2021-02-24 17:15:17,283 INFO z925: 0 orders created
2021-02-24 17:15:17,284 INFO mcc: 0 orders created
2021-02-24 17:15:17,284 INFO t2m: 0 orders created
2021-02-24 17:15:17,284 INFO zt500: 0 orders created
2021-02-24 17:15:17,284 INFO z500: 0 orders created
2021-02-24 17:15:17,284 INFO wmax: 0 orders created
Traceback (most recent call last):
  File "./arkimaps", line 365, in <module>
    main()
  File "./arkimaps", line 356, in main
    res = handler.run()
  File "./arkimaps", line 305, in run
    self.render_tarball()
  File "./arkimaps", line 106, in render_tarball
    for order in renderer.render(orders):
  File "/autofs/nfshomes/dbranchini/git/arkimaps/arkimapslib/render.py", line 62, in render
    yield from pool.imap_unordered(prepare_order, orders)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
    put(task)
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 210, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib64/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects
```

**Comment by brancomat** [comment]
Confermo, l'attuale master gira correttamente su CentOS8 / python 3.6
