### ISSUE TITLE
errori assortiti dopo ultimo refactoring

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#58]
A seguito del refactoring della #27 non riesco più a produrre le mappe dai grib (che allego: [grib2_ifs.tar.gz](https://github.com/ARPA-SIMC/arkimaps/files/6068789/grib2_ifs.tar.gz) ) né a fare un dispatch:

errore con `dispatch`:
```
$ ./arkimaps --debug dispatch t1 < test_data/grib2_ifs.arkimet
2021-03-02 14:08:11,855 INFO cpdec3h (model=None): skipping input with no arkimet matcher filter
2021-03-02 14:08:11,855 INFO cpdec6h (model=None): skipping input with no arkimet matcher filter
2021-03-02 14:08:11,855 INFO cpdec12h (model=None): skipping input with no arkimet matcher filter
2021-03-02 14:08:11,856 INFO cpdec24h (model=None): skipping input with no arkimet matcher filter
2021-03-02 14:08:11,856 INFO rh2m (model=cosmo): skipping input with no arkimet matcher filter
2021-03-02 14:08:11,856 INFO rh2m (model=ifs): skipping input with no arkimet matcher filter
2021-03-02 14:08:11,856 INFO tpdec1h (model=None): skipping input with no arkimet matcher filter
2021-03-02 14:08:11,856 INFO tpdec3h (model=None): skipping input with no arkimet matcher filter
2021-03-02 14:08:11,856 INFO tpdec6h (model=None): skipping input with no arkimet matcher filter
2021-03-02 14:08:11,856 INFO tpdec12h (model=None): skipping input with no arkimet matcher filter
2021-03-02 14:08:11,856 INFO tpdec24h (model=None): skipping input with no arkimet matcher filter
Traceback (most recent call last):
  File "./arkimaps", line 365, in <module>
    main()
  File "./arkimaps", line 356, in main
    res = handler.run()
  File "./arkimaps", line 218, in run
    self.kitchen.pantry.fill(self.kitchen.recipes)
  File "/home/branco/git/arkimaps/arkimapslib/pantry.py", line 149, in fill
    with self.open_dispatch_input(path=path) as infd:
  File "/usr/lib64/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/branco/git/arkimaps/arkimapslib/pantry.py", line 89, in open_dispatch_input
    with open(path, "rb") as fd:
TypeError: expected str, bytes or os.PathLike object, not Recipes
```

errori con `process`:
```
$ ./arkimaps process -o out.tar < test_data/grib2_ifs.arkimet
Magics-ERROR: can not access position [2 in /tmp/tmpk48pql4b/pantry/any_viwve+3.grib]

Magics-ERROR: can not access position [2 in /tmp/tmpk48pql4b/pantry/any_viwve+3.grib]

Magics-ERROR: Errors reported:can not access position [2 in /tmp/tmpk48pql4b/pantry/any_viwve+3.grib]
 - No plot produced  

Magics-ERROR: 
Magics-ERROR: can not access position [2 in /tmp/tmpk48pql4b/pantry/any_litota3+90.grib]

Magics-ERROR: can not access position [2 in /tmp/tmpk48pql4b/pantry/any_litota3+90.grib]

Magics-ERROR: Errors reported:can not access position [2 in /tmp/tmpk48pql4b/pantry/any_litota3+90.grib]
 - No plot produced  

Magics-ERROR: 
Magics-ERROR: can not access position [2 in /tmp/tmpk48pql4b/pantry/any_litota3+87.grib]

Magics-ERROR: can not access position [2 in /tmp/tmpk48pql4b/pantry/any_litota3+87.grib]

Magics-ERROR: Errors reported:can not access position [2 in /tmp/tmpk48pql4b/pantry/any_litota3+87.grib]
 - No plot produced  

Magics-ERROR: 
Magics-ERROR: can not access position [2 in /tmp/tmpk48pql4b/pantry/any_litota3+84.grib]

Magics-ERROR: can not access position [2 in /tmp/tmpk48pql4b/pantry/any_litota3+84.grib]

Magics-ERROR: Errors reported:can not access position [2 in /tmp/tmpk48pql4b/pantry/any_litota3+84.grib]
 - No plot produced  

Magics-ERROR: 
Magics-ERROR: can not access position [2 in /tmp/tmpk48pql4b/pantry/any_litota3+81.grib]

Magics-ERROR: can not access position [2 in /tmp/tmpk48pql4b/pantry/any_litota3+81.grib]

Magics-ERROR: Errors reported:can not access position [2 in /tmp/tmpk48pql4b/pantry/any_litota3+81.grib]
 - No plot produced  

Magics-ERROR: 
Magics-ERROR: can not access position [2 in /tmp/tmpk48pql4b/pantry/any_litota3+78.grib]

Magics-ERROR: can not access position [2 in /tmp/tmpk48pql4b/pantry/any_litota3+78.grib]

Magics-ERROR: Errors reported:can not access position [2 in /tmp/tmpk48pql4b/pantry/any_litota3+78.grib]
 - No plot produced  

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/branco/git/arkimaps/arkimapslib/render.py", line 14, in prepare_order
    order.prepare(workdir)
  File "/home/branco/git/arkimaps/arkimapslib/recipes.py", line 157, in prepare
    mixer.serve()
  File "/home/branco/git/arkimaps/arkimapslib/mixer.py", line 266, in serve
    self.macro.plot(
  File "/usr/lib/python3.8/site-packages/Magics/macro.py", line 763, in _plot
    Magics.finalize()
  File "/usr/lib/python3.8/site-packages/Magics/Magics.py", line 176, in wrapped
    raise MagicsError(err)
Magics.Magics.MagicsError: Magics Error - No Plot Produced!!! (406152208)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./arkimaps", line 365, in <module>
    main()
  File "./arkimaps", line 356, in main
    res = handler.run()
  File "./arkimaps", line 305, in run
    self.render_tarball()
  File "./arkimaps", line 106, in render_tarball
    for order in renderer.render(orders):
  File "/home/branco/git/arkimaps/arkimapslib/render.py", line 65, in render
    yield from pool.imap_unordered(prepare, orders)
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
Magics.Magics.MagicsError: Magics Error - No Plot Produced!!! (Magics Error - No Plot Produced!!! (406152208))
```
(log completo con `--debug`: [full_log.txt](https://github.com/ARPA-SIMC/arkimaps/files/6068827/full_log.txt) )

```

**Comment by spanezz** [comment]
Ho risolto i vari problemi, ma rimane che per alcuni prodotti Magics dà un errore e non capisco il perché.

Ho cambiato il codice in modo da loggare l'errore e non interrompere la processazione.

**Comment by brancomat** [comment]
Gli errori di magics non sembrano completamente deterministici (run diversi a partire dagli stessi dati falliscono su scadenze leggermente diverse), forse qualcosa legato alla parallelizzazione? Ho fatto un test empirico dalla valenza statistica dubbia e gli errori sembrano in qualche modo proporzionali al settaggio di `maxtasksperchild` in `render.py`, anche se impostandolo a 1 mi dà comunque almeno un errore.

Però la versione pre-multiprod attualmente operativa sugli stessi dati non sbaglia un colpo.

**Comment by brancomat** [comment]
Esiti di ulteriori analisi:
1) c'è un problema aggiuntivo che complica la vita: il dispatch con il default `--filter=arkimet` non prepara i dati relativi al product `viwvn` ma solo quelli per `viwne`, questo è un problema diverso, riapro la #56, ma il succo è che per i test tocca usare `--filter=eccodes`
2) non riesco a riprodurre gli errori che mi arrivano da un `process` se faccio prima il `dispatch` e poi la `preview`, ovvero: i prodotti su cui esplode durante il `process` vengono mostrati correttamente in `preview`. Questo forse confermerebbe l'ipotesi di problemi legati alla parallelizzazione.

**Comment by spanezz** [comment]
C'era un bug nella scelta di quali file di input associare ai nomi degli input nelle ricette. Visto l'errore nel codice, la cosa fastidiosa era che mediamente andasse pure, e se Python avesse regole di scoping meno spensierate, quel codice non avrebbe nemmeno dovuto compilare.

Ad ogni modo, ora mi sembra risolto, e ci abbiamo guadagnato che ora nella directory di lavoro viene generato un file python per ogni prodotto, utile a riprodurre il problema se si ripresentano altri scoppi in magics

**Comment by brancomat** [comment]
Ottimo, visto file di debug python, ho generato un paio di run completi con COSMO e IFS, tutto regolare
