### ISSUE TITLE
input nei flavour non considerato

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#72]
in https://github.com/ARPA-SIMC/arkimaps/blob/master/recipes/flavours/default.yaml ho definito i seguenti input:
```
inputs:
  sottozone_allerta_er:
    type: shape
    path: shapes/Sottozone_allerta_ER
  punti_citta:
    type: static
    path: puntiCitta.geo
```

sembra però che `punti_citta` non arrivi a `steps.py` (nota: invertendo l'ordine della definizione degli input l'input che manca è sempre `punti_citta`):

```
[branco@kinotto arkimaps]$ ./arkimaps preview --flavour emro t2/ wflags250+024
Traceback (most recent call last):
  File "./arkimaps", line 413, in <module>
    main()
  File "./arkimaps", line 404, in main
    res = handler.run()
  File "./arkimaps", line 317, in run
    order = self.kitchen.make_order(self.kitchen.recipes.get(name), step, flavour=flavour)
  File "/home/branco/git/arkimaps/arkimapslib/kitchen.py", line 132, in make_order
    for o in recipe.make_orders(self.pantry, flavour=flavour):
  File "/home/branco/git/arkimaps/arkimapslib/recipes.py", line 190, in make_orders
    res.append(orders.Order(
  File "/home/branco/git/arkimaps/arkimapslib/orders.py", line 42, in __init__
    s = recipe_step.instantiate(self.flavour, sources)
  File "/home/branco/git/arkimaps/arkimapslib/recipes.py", line 55, in instantiate
    return self.step(self.name, step_config, self.args, sources)
  File "/home/branco/git/arkimaps/arkimapslib/steps.py", line 301, in __init__
    raise KeyError(f"{self.name}: input {input_name} not found. Available: {', '.join(sources.keys())}")
KeyError: 'add_geopoints: input punti_citta not found. Available: uv250, sottozone_allerta_er'
```

l'utile e rapidissimamente implementato `dump-recipes` li mostra:
```
  "sottozone_allerta_er": [
   {
    "name": "sottozone_allerta_er",
    "type": "shape",
    "model": null,
    "defined_in": "flavours/default.yaml",
    "mgrib": null,
    "pantry_basename": "sottozone_allerta_er",
    "abspath": "/home/branco/git/arkimaps/arkimapslib/static/shapes/Sottozone_allerta_ER",
    "path": "shapes/Sottozone_allerta_ER"
   }
  ],
  "punti_citta": [
   {
    "name": "punti_citta",
    "type": "static",
    "model": null,
    "defined_in": "flavours/default.yaml",
    "mgrib": null,
    "pantry_basename": "punti_citta",
    "abspath": "/home/branco/git/arkimaps/arkimapslib/static/puntiCitta.geo",
    "path": "puntiCitta.geo"
   }
  ]
```

**Comment by spanezz** [comment]
Giusto! Quando cerca quali input siano effettivamente usati, lo fa scorrendo solo le ricette, e quindi gli input definiti solo nei flavour vengono persi.

Ora ragiono di come sistemare la cosa
