### ISSUE TITLE
validazione input

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#85]
Al momento arkimaps non verifica nel dettaglio i grib che gli vengono dati in pasto.
Non so quanto sia complesso a livello implementativo ma ad un livello zero credo sarebbe una buona cosa che desse un warning se nei file del dispatch ci finisce roba che non dovrebbe esserci, ad esempio:

- più di un grib per step per le variabili singole
- più di due grib di componenti (auspicabilmente diversi, u e v o wdir e wspeed) per il vento

e così via.

Una volta "riempito" quello step il resto andrebbe scartato con un warning in modo da non impattare sui plot.

**Comment by spanezz** [comment]
Ora vengono loggati errori se ci sono piú GRIB prodotti per uno step, sia dal filtraggio iniziale che dai postprocessatori.

Nei test ho visto che nelle decumulate, `vg6d_transform --comp-stat-proc=1 -comp-step="0 3 --comp-frac-valid=0 --comp-full-steps` può produrre piú di un grib per step, ma non saprei trarre conclusioni dalla cosa.

Vi chiederei di far girare i casi che producevano u e v sbagliati per vedere se i warning attuali sono sufficienti per gestire la situazione, o se serve anche andare a vedere che le componenti per il vento siano u e v o quello che devono essere.

In teoria il fatto che siano u e v povrebbe essere garantito dai warning negli input che vengono poi composti assieme per il vento; non so se sia sufficiente contare gli elementi o serva qualcosa di meglio

**Comment by brancomat** [comment]
Dunque, ho fatto un po' di test, seguono responsi, parto dalle quisquilie:

**1  - se si può sarebbe meglio declassare gli `ERROR`  a `WARNING` (come messaggio)**
I warning sono quelli che mi aspetterei, ma visto che arkimaps postprocessa quel che riesce ed esce comunque con exit 0 mi pare avrebbero più senso come warning

Questi gli output dei test:
```
$ ./arkimaps dispatch t1 < test_data/erg5v15_20210927.arkimet 
2021-11-16 16:46:51,465 ERROR arkimaps.inputs t2m: multiple data found for step +0
2021-11-16 16:46:51,465 ERROR arkimaps.inputs rh2m: multiple data found for step +0
2021-11-16 16:46:51,465 ERROR arkimaps.inputs ws10m: multiple data found for step +0
2021-11-16 16:46:51,465 ERROR arkimaps.inputs t2m: multiple data found for step +0
2021-11-16 16:46:51,465 ERROR arkimaps.inputs rh2m: multiple data found for step +0
2021-11-16 16:46:51,466 ERROR arkimaps.inputs wdir10m: multiple data found for step +0
2021-11-16 16:46:51,466 ERROR arkimaps.inputs ws10m: multiple data found for step +0
2021-11-16 16:46:51,466 ERROR arkimaps.inputs t2m: multiple data found for step +0
2021-11-16 16:46:51,466 ERROR arkimaps.inputs rh2m: multiple data found for step +0

$ ./arkimaps dispatch t2 < test_data/ifs010.arkimet 
2021-11-16 16:47:16,763 ERROR arkimaps.inputs t925: multiple data found for step +0
2021-11-16 16:47:16,763 ERROR arkimaps.inputs z700: multiple data found for step +0
2021-11-16 16:47:16,763 ERROR arkimaps.inputs z250: multiple data found for step +0
2021-11-16 16:47:16,764 ERROR arkimaps.inputs v700: multiple data found for step +0
2021-11-16 16:47:16,764 ERROR arkimaps.inputs u700: multiple data found for step +0
2021-11-16 16:47:16,764 ERROR arkimaps.inputs v850: multiple data found for step +0
2021-11-16 16:47:16,764 ERROR arkimaps.inputs u850: multiple data found for step +0
2021-11-16 16:47:16,764 ERROR arkimaps.inputs z850: multiple data found for step +0
2021-11-16 16:47:16,764 ERROR arkimaps.inputs z925: multiple data found for step +0
2021-11-16 16:47:16,764 ERROR arkimaps.inputs u925: multiple data found for step +0
2021-11-16 16:47:16,765 ERROR arkimaps.inputs v925: multiple data found for step +0
2021-11-16 16:47:16,765 ERROR arkimaps.inputs z500: multiple data found for step +0
2021-11-16 16:47:16,765 ERROR arkimaps.inputs u250: multiple data found for step +0
2021-11-16 16:47:16,765 ERROR arkimaps.inputs v250: multiple data found for step +0
2021-11-16 16:47:16,765 ERROR arkimaps.inputs t850: multiple data found for step +0
2021-11-16 16:47:16,765 ERROR arkimaps.inputs t700: multiple data found for step +0
2021-11-16 16:47:16,766 ERROR arkimaps.inputs t500: multiple data found for step +0
2021-11-16 16:47:16,766 ERROR arkimaps.inputs u500: multiple data found for step +0
2021-11-16 16:47:16,766 ERROR arkimaps.inputs v500: multiple data found for step +0
```

**2  - problemi nella combo `dispatch` + `preview` (o `render`)**

Stavo provando ad approfondire questa parte:

> Vi chiederei di far girare i casi che producevano u e v sbagliati per vedere se i warning attuali sono sufficienti per gestire la situazione, o se serve anche andare a vedere che le componenti per il vento siano u e v o quello che devono essere.

Però se al posto di `process` uso `dispatch` + `preview` (o `render`) sembra non accorgersi di avere gli input a disposizione e non crea nulla.

**3 - presenza dati duplicati nel `dispatch`**

Qui forse sono io che ho interpretato male, ma mi aspettavo (anche per evitare casini nel postprocessamento) che ad ogni warning/error corrispondesse un discard del dato che arriva per secondo, cosa che fra l'altro permetterebbe di essere ragionevolmente certi ad esempio per il vento che il postprocessamento vada a combinare due messaggi grib per ogni step e non di più.
Invece col dispatch noto (esempio):
```
$ ./arkimaps dispatch t1 < test_data/ifs010.arkimet 
2021-11-16 16:53:01,918 ERROR arkimaps.inputs v700: multiple data found for step +0
2021-11-16 16:53:01,918 ERROR arkimaps.inputs u700: multiple data found for step +0
$ grib_ls t1/pantry/ifs_t700+0.grib 
t1/pantry/ifs_t700+0.grib
edition      centre       typeOfLevel  level        dataDate     stepRange    dataType     shortName    packingType  gridType     
1            ecmf         isobaricInhPa  700          20211116     0            an           t            grid_simple  regular_ll  
1            ecmf         isobaricInhPa  700          20211116     0            fc           t            grid_simple  regular_ll  
1            ecmf         isobaricInhPa  700          20211116     0            an           t            grid_simple  regular_ll  
1            ecmf         isobaricInhPa  700          20211116     0            fc           t            grid_simple  regular_ll  
4 of 4 messages in t1/pantry/ifs_t700+0.grib

4 of 4 total messages in 1 files
```

**Comment by spanezz** [comment]
Ho declassato gli error a warning.

Tenere un solo grib è inaspettatamente complesso: non è arkimaps che aggiunge i grib aggiuntivi al file, ma grib_filter. Io mi faccio stampare da grib_filter che cosa ha fatto, ma non posso dirgli "fermati al primo".

Forse posso farmi stampare quanto è grande il grib che ha appena copiato, e troncare il file dopo il primo? Provo.

Poi provo anche a debuggare la differenza di comportamento nel dispatch+preview rispetto al process

**Comment by dcesari** [comment]
> Nei test ho visto che nelle decumulate, vg6d_transform --comp-stat-proc=1 -comp-step="0 3" --comp-frac-valid=0 --comp-full-steps può produrre piú di un grib per step, ma non saprei trarre conclusioni dalla cosa.

hai un caso d'uso per verificare questo, in modo da capire? Immagino che stiamo comunque parlado di forecast, non ancora di analisi, giusto?

**Comment by spanezz** [comment]
> hai un caso d'uso per verificare questo, in modo da capire? Immagino che stiamo comunque parlado di forecast, non ancora di analisi, giusto?

Ho provato a generare il caso d'uso per verificarlo, e non ci sono riuscito. Ho invece trovato un bug nella contabilità dei passi generati da grib_filter, e l'ho risolto. Ora va tutto bene :)

**Comment by spanezz** [comment]
Risolvendo il bug sul conteggio dei grib generati da `grib_filter`, sparisce il bug in caso di dispatc+render.

Rimane aperta solo la richiesta di troncare i grib a solo il primo elemento. Possibili strategie:

* se esiste una chiave di eccodes che mi dà la lunghezza di un grib in byte, la posso stampare in grib_filter e troncare alla lunghezza del primo messaggio scritto
* altrimenti, quando trovo la discrepanza posso aprire il file con eccodes per avere la lunghezza del primo elemento, e poi troncare

È piú lento riaprire il grib, ma visto che si fa solo in caso di dati doppi e stampando un warning, non dovrebbe essere il caso comune

**Comment by spanezz** [comment]
Ho implementato una via di mezzo: i grib duplicati all'interno dello stesso step, che risultano dal filtraggio iniziale, vengono troncati.

I grib duplicati potenzialmente scritti da vg6d_transform, vengono loggati facendo notare che il troncaggio non è implementato.

Questo perché al momento non ho un esempio di vg6d_transform che duplichi input, e rischio di scrivere codice non testabile per un caso che non si proporrà mai.

Con questo dovrei aver gestito tutti i punti del feedback din @brancomat

**Comment by brancomat** [comment]
Grazie! Tutto bene tranne `preview` / `render` che ancora apparentemente non funziona, riassumo test che ho fatto e allego test data ([ifs.tar.gz](https://github.com/ARPA-SIMC/arkimaps/files/7561294/ifs.tar.gz)):

```
[branco@kinotto arkimaps]$ arki-query --inline 'Reftime:=2021-10-07 00:00;product:GRIB1,98,128,130 or GRIB1,98,128,131 or GRIB1,98,128,132 or GRIB1,98,128,156;level:GRIB1,100,850' http://arkimet.metarpa:8090/dataset/ifs_ita010_arc > test_data/ifs_ita010_test.arkimet

[branco@kinotto arkimaps]$ ./arkimaps process --flavour=emro < test_data/ifs_ita010_test.arkimet |tar -xf - -C out/
2021-11-18 09:30:07,886 WARNING arkimaps.inputs t850: multiple data found for step +0
2021-11-18 09:30:07,886 WARNING arkimaps.inputs z850: multiple data found for step +0
2021-11-18 09:30:07,887 WARNING arkimaps.inputs v850: multiple data found for step +0
2021-11-18 09:30:07,887 WARNING arkimaps.inputs u850: multiple data found for step +0
[branco@kinotto arkimaps]$ ls out/
log.json         t850_emro/       warrows850_emro/ wflags850_emro/  z850_emro/       ztw850_emro/     
[branco@kinotto arkimaps]$ ls -la out/ztw850_emro/ztw850+000.png 
-rw-rw-r-- 1 branco branco 161800 18 nov 09.30 out/ztw850_emro/ztw850+000.png

[branco@kinotto arkimaps]$ ./arkimaps dispatch t1/ < test_data/ifs_ita010_test.arkimet
2021-11-18 09:31:38,447 WARNING arkimaps.inputs t850: multiple data found for step +0
2021-11-18 09:31:38,447 WARNING arkimaps.inputs z850: multiple data found for step +0
2021-11-18 09:31:38,448 WARNING arkimaps.inputs v850: multiple data found for step +0
2021-11-18 09:31:38,448 WARNING arkimaps.inputs u850: multiple data found for step +0
[branco@kinotto arkimaps]$ ./arkimaps preview --flavour=emro t1 ztw850+000
Traceback (most recent call last):
  File "/home/branco/git/arkimaps/./arkimaps", line 412, in <module>
    main()
  File "/home/branco/git/arkimaps/./arkimaps", line 403, in main
    res = handler.run()
  File "/home/branco/git/arkimaps/./arkimaps", line 339, in run
    order = self.kitchen.make_order(self.kitchen.recipes.get(name), step, flavour=flavour)
  File "/home/branco/git/arkimaps/arkimapslib/kitchen.py", line 140, in make_order
    raise RuntimeError(f"not enough data to prepare {recipe.name}+{step:03d}")
RuntimeError: not enough data to prepare ztw850+000

[branco@kinotto arkimaps]$  ./arkimaps render --flavour=emro t1 | tar -xf - -C out2/
[branco@kinotto arkimaps]$ ls out2/
log.json

**Comment by spanezz** [comment]
Ho capito il problema: di recente ho ristrutturato internamente il codice per segnarsi a tempo di dispatch cosa è stato messo in pantry. Dividendo dispatch e render, queste informazioni vengon perse, e la pantry sembra vuota.

Ora lo riproduco in un test, e aggiungo un metodo di rescan della pantry per le operazioni che non contengono un dispatch

**Comment by spanezz** [comment]
Ho fatto push di test e fix. Forse ci siamo?

**Comment by brancomat** [comment]
Yesss, tutto ok, chiudo issue.
